### PR TITLE
Updated css

### PR DESCRIPTION
**Pull request by VkRan**
Added sample scrolling effect

### CODE REVIEW

**Comment by krutarththakkar** [comment]
Nice one!
Thanks

**Comment by VkRan** [comment]
But bro my PR didn't add to my Hacktoberfest PRs. I really need to complete
it. Plz if you can label it

Edit: Well you have done it I guess, but it's not showing on my profile. I guess, I've to wait for some time. Thanks buddy

**Comment by krutarththakkar** [comment]
On that note,
There is a 14 day Review period after any PR is accepted,
As long as the PR was made in October and isnt called SPAM in the 14 days,
It counts(Refer to FAQ on hacktoberfest to know more)

**Comment by krutarththakkar** [comment]
I'd Appreciate if you could add a README.md for your snippet and make it easier for people to use your snippet
Make sure to add a gif of the code in action!
Though even a screen capture works with windows snip and sketch(pre-installed)
For screen record try [WIN+G](https://www.pcmag.com/how-to/how-to-capture-video-clips-in-windows-10)

**Comment by krutarththakkar** [comment]
Though even a screen capyure works with windows snip and sketch(pre-installed)
For screen record try [WIN+G](https://www.pcmag.com/how-to/how-to-capture-video-clips-in-windows-10)

**Comment by VkRan** [comment]
Sure bro, I will do it as soon as possible. Just a little busy rn with the
online sem.
Bdw it worked now when you merged it with the main branch

**Pull request merged**
